### PR TITLE
Update to v0.0.3

### PR DESCRIPTION
**Pull request by erikmannerfelt**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erikmannerfelt** [comment]
I still don't know what made it so that this didn't update automatically. Perhaps because of @adehecq 's versions "v0.0.2", "v0.02" and "0.02"? ;)

**Comment by erikmannerfelt** [comment]
@conda-forge-admin, please rerender

**Comment by erikmannerfelt** [comment]
@conda-forge-admin please rerender

**Comment by adehecq** [comment]
> I still don't know what made it so that this didn't update automatically. Perhaps because of @adehecq 's versions "v0.0.2", "v0.02" and "0.02"? ;)

Haha sorry for the mess!

**Pull request merged**
